name: Auto Update Test

on: workflow_dispatch
  # schedule:
  #   # Runs 8:7 UTC every day -  10:7 SAST
  #   - cron: "*/6 * * * *"

jobs:
  auto-update-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run JavaScript name function
      run: |
        node -e "const fs = require('fs');
        const path = './my-file.txt';
        const UTE_MAPPING = [
            ['Login','biometric_login', 'login'],
            ['Login','biometric_login', 'impression'],
            ['Login','biometric_login', 'error_impression'],
            ['Settings','settings', 'impression'],
            ['Settings','notification_settings', 'Impression'],
            ['Settings','security_Settings', 'impression'],
        ]

        // Generate a LookML script to add all mapped user tracking event fields as dimensions and measures
        function makeLookML() {
            let lookML = [];

            for (const [header, context, action] of UTE_MAPPING) {
              let lowContext = context.toLowerCase();
              let lowAction = action.toLowerCase();
              const fieldName = \`\${lowContext}_\${lowAction}\`.replace(/[.-]/g, '_');

              var dimension = 'dimension: '+fieldName+' {\\n\\thidden: yes\\n\\tgroup_label: \"'+header+'\"\\n\\ttype: number\\n\\tsql: \\${TABLE}.'+fieldName+'\\;\\;\\n}\\n';
              var measure = 'measure: total_'+fieldName+' {\\n\\tlabel: \"'+context+':'+action+'\"\\n\\tgroup_label: \"'+header+'\"\\n\\ttype: sum\\n\\tvalue_format: \"@{number_format}\"\\n\\tsql: \\${'+fieldName+'}\\;\\;\\n}\\n';
              lookML.push(dimension);
              lookML.push(measure);
            }

          return lookML.join('\\n');
        }

        // Append string to existing file
        function appendDateToFile(filePath) {
          const currentDate = new Date().toISOString();
          fs.appendFileSync(filePath, 'test');
        }

        // Execute the function
        appendDateToFile(path);
        "

    - name: Commit changes and push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update: $(date)"
        git push
