name: Auto Update Test

on: workflow_dispatch
  # schedule:
  #   # Runs 8:7 UTC every day -  10:7 SAST
  #   - cron: "*/6 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Run JavaScript script
      run: node test-js.js

    - name: Commit changes and push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated update: $(date)"
        git push
